default_session = "luizg"
excluded_dirs = [
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
    "/home/luizg/.config/tmux/plugins/tmux-battery",
    "/home/luizg/.config/tmux/plugins/tmux-better-mouse-mode",
    "/home/luizg/.config/tmux/plugins/tmux-cpu",
    "/home/luizg/.config/tmux/plugins/tmux-gruvbox",
    "/home/luizg/.config/tmux/plugins/tmux-nerd-font-window-name",
    "/home/luizg/.config/tmux/plugins/tmux-open",
    "/home/luizg/.config/tmux/plugins/tmux-sensible",
    "/home/luizg/.config/tmux/plugins/tmux-thumbs",
    "/home/luizg/.config/tmux/plugins/tpm",
    "/home/luizg/.config/tmux/plugins/vim-tmux-navigator",
]
bookmarks = [
    "/home/luizg",
    "/home/luizg/.config",
    "/home/luizg/Documents/Faculdade/Semestre7/SistemasDistribuidos",
    "/home/luizg/Documents/Faculdade/Semestre7/TDSOFT",
    "/home/luizg/Documents/Personal/Projects",
]

[[search_dirs]]
path = "/home/luizg/Documents"
depth = 10

[[search_dirs]]
path = "/home/luizg/.config"
depth = 10

[[search_dirs]]
path = "/home/luizg/Documents/Personal/Projects"
depth = 10
