# Fonts
font_family  Fira Code Regular
bold_font Fira Code, Bold
italic_font Fira Code, Regular Italic
bold_italic_font Fira Code, Bold Italic
font_size 12
disable_ligatures cursor
force_ltr no
font_features FiraCode-Regular +zero +onum

# Mouse
cursor #fff
mouse_hide_wait -1
focus_follows_mouse no

# URL
url_color #00f
url_style dashed
detect_urls yes

# Performance
sync_to_monitor yes

# Terminal Bell
visual_bell_duration 0.0
bell_on_tab "🔔 "

# Windows
window_margin_width 1
draw_minimal_borders yes
single_window_margin_width 0
window_padding_width 1
placement_strategy center
active_border_color #f0c
inactive_text_alpha 0.3
map ctrl+left neighboring_window left
map ctrl+up neighboring_window up
map ctrl+right neighboring_window right
map ctrl+down neighboring_window down
map shift+left move_window left
map shift+up move_window up 
map shift+right move_window right
map shift+down move_window down 

# Color Scheme

foreground #dddddd
background #000
background_opacity 0.93
dynamic_background_opacity yes

startup_session ~/.config/kitty/sessions/default

# Shell
shell zsh

# Editor
editor nvim

# Display server
linux_display_server auto 
